# src/main/resources/application.yml
spring:
  config:
    import: optional:file:.env[.properties]  # добавил: перемещено в начало для глобальной подстановки ${JWT_SECRET} и других
  main:
    banner-mode: off
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
---
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml  # изменил: исправлен путь к changelog-master.yaml
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha
      groups-order: explicit
      group-configs:
        - group: auth
          paths-to-match: /api/auth/**
        - group: admin
          paths-to-match: /api/admin/**
        - group: user
          paths-to-match: /api/user/**
logging:
  level:
    com.example.bankcards: INFO