spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/bankrest
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
jwt: # изменил: добавил rotation-interval в существующую секцию
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  rotation-interval: ${JWT_ROTATION_INTERVAL:86400000} # добавил: для dev (24ч по умолчанию)
encryption: # Шифрование
  secret: ${ENCRYPTION_SECRET} # Секрет для шифрования (AES, OWASP: безопасный для секретов).
server:
  port: ${SERVER_PORT}