# добавленный код: Активация профиля по умолчанию.
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# добавленный код: Общие настройки сервера.
server:
  port: ${SERVER_PORT:8080}

# добавленный код: Логирование (SLF4J по умолчанию в Spring).
logging:
  level:
    root: INFO
    com.example.bankcards: DEBUG  # добавленный код: Уровень логирования для пакета проекта.