spring:
  main:
    banner-mode: off
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
jwt: # добавил: секция для JWT (OWASP: централизованная конфигурация ключей)
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  rotation-interval: ${JWT_ROTATION_INTERVAL:86400000} # добавил: интервал ротации ключей в ms (по умолчанию 24ч; используй в @Scheduled)
---
spring:
  config:
    import: file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
     change-log: classpath:db/changelog/changelog-master.yaml
logging:
  level:
    com.example.bankcards: INFO