spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    enabled: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  rotation-interval: ${JWT_ROTATION_INTERVAL:3600000}
encryption:
  secret-key: ${ENCRYPTION_SECRET}
server:
  port: ${SERVER_PORT}
logging:
  level:
    root: WARN
    com.example.bankcards: INFO