# src/main/resources/application-dev.yml
spring:
  config:
    import: optional:file:.env[.properties]  # добавлено: явный импорт для dev профиля (для подстановки ${JWT_SECRET})
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/bankrest
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
jwt:  # секция остаётся без изменений, но теперь ${JWT_SECRET} подставится
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  rotation-interval: ${JWT_ROTATION_INTERVAL:86400000}
encryption:  # секция остаётся без изменений
  secret: ${ENCRYPTION_SECRET}
server:
  port: ${SERVER_PORT}
logging:
  level:
    org.springframework.boot.context.config: DEBUG  # добавлено: для отладки подстановки ${JWT_SECRET}
    com.example.bankcards.util: DEBUG  # добавлено: для логов JwtUtilImpl