# src/main/resources/application.yml
spring:
  config:
    import: optional:file:.env[.properties]  # изменено: перемещено в начало для глобальной подстановки ${JWT_SECRET} и других
  main:
    banner-mode: off
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
---
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
logging:
  level:
    com.example.bankcards: INFO