spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
#    hibernate:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        default_schema: bankrest
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    enabled: true
    default-schema: public # Liquibase ведёт свою историю здесь
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  rotation-interval: ${JWT_ROTATION_INTERVAL:86400000}
encryption:
  secret-key: ${ENCRYPTION_SECRET}
server:
  port: ${SERVER_PORT}
logging:
  level:
    org.springframework.boot.context.config: DEBUG
    com.example.bankcards.util: DEBUG