spring:
  config:
    import: optional:file:.env[.properties]
  main:
    banner-mode: off
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha
      groups-order: explicit
      group-configs:
        - group: auth
          paths-to-match: /api/auth/**
        - group: admin
          paths-to-match: /api/admin/**
        - group: user
          paths-to-match: /api/user/**
logging:
  level:
    com.example.bankcards: INFO