spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/bankrest
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
encryption: # изменил ИИ: добавил секцию encryption для конфигурации секрета AES (OWASP: внешняя конфигурация secrets).
  secret: ${ENCRYPTION_SECRET} # добавленный код: свойство для секрета шифрования, загружается из .env (соответствие современным практикам: переменные окружения).
server:
  port: ${SERVER_PORT}