#spring:
#  datasource:
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5434}/bankrest
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#  liquibase:
#    change-log: classpath:db/migration/changelog-master.yaml
#jwt:
#  secret: ${JWT_SECRET}
#  expiration: ${JWT_EXPIRATION:86400000}
#server:
#  port: ${SERVER_PORT:8082}
#logging:
#  level:
#    root: WARN