#paths:
#  /api/user/transactions/transfer:  # изменил: путь эндпоинта.
#    post:
#      summary: Перевод между картами пользователя  # добавил: описание.
#      operationId: transferFunds  # добавил: уникальный ID.
#      security:
#        - bearerAuth: []  # добавил: JWT, OWASP: secure endpoint.
#      tags:
#        - User  # добавил: группировка в UI.
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#              required: [fromCardId, toCardId, amount]  # добавил: обязательные поля.
#              properties:  # изменил: минимальная схема.
#                fromCardId:
#                  type: integer
#                  format: int64
#                  description: ID карты-отправителя
#                toCardId:
#                  type: integer
#                  format: int64
#                  description: ID карты-получателя
#                amount:
#                  type: number
#                  format: double
#                  minimum: 0.01
#                  description: Сумма перевода
#            example:  # изменил: пример без чувствительных данных, OWASP.
#              fromCardId: 1
#              toCardId: 2
#              amount: 100.00
#      responses:
#        '200':
#          description: Перевод успешен
#          content:
#            application/json:
#              schema:
#                type: object
#                properties:  # изменил: минимальный ответ.
#                  fromCardId:
#                    type: integer
#                    format: int64
#                  toCardId:
#                    type: integer
#                    format: int64
#                  amount:
#                    type: number
#                    format: double
#              example:
#                fromCardId: 1
#                toCardId: 2
#                amount: 100.00
#        '400':
#          description: Неверные данные (например, недостаточно средств)
#        '403':
#          description: Доступ запрещён
#        '404':
#          description: Карта не найдена