openapi: 3.0.3
info:
  title: Bank Cards API
  version: 1.0.0
  description: API для управления банковскими картами
servers:
  - url: http://localhost:8080
    description: Dev server

# Настройки для Swagger UI
x-swagger-ui-init:
  docExpansion: none  # Все элементы свёрнуты по умолчанию
  defaultModelsExpandDepth: -1  # Схемы данных скрыты
  displayRequestDuration: true
  tryItOutEnabled: true

paths:
  /api/admin/cards/create/{userId}:
    post:
      summary: Create a new card for a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardCreationDTO'
            example:
              name: "Divan McDivan"
      responses:
        '200':
          description: Card created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardDTO'

components:
  schemas:
    CardCreationDTO:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    CardDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        number:
          type: string
        expiration:
          type: string
        cvv:
          type: string
        balance:
          type: number
        status:
          type: string